# .cpanel.yml  – cPanel will read this automatically
---
deployment:
  # run on “Deploy HEAD Commit” or “Update from Remote”
  tasks:
    - echo "→ Building Attune-Web…"
    - cd $repository
    - npm install --production
    - npm run build
    - echo "→ Copying to public_html…"
    - rm -rf ~/public_html/*
    - cp -R dist/* ~/public_html/
